# Generated by Django 5.1.3 on 2024-12-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='contact_details',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
