# Generated by Django 5.1.3 on 2024-12-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_manage', '0002_remove_leaveapplication_contact_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='annual_allocation',
        ),
    ]
